# Generated by Django 3.1 on 2021-01-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_remunerador', models.CharField(blank=True, max_length=50)),
                ('portaria_bolsa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº da Portaria')),
                ('data_de_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_de_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('portaria_projeto', models.PositiveIntegerField(verbose_name='Nº da Portaria')),
                ('data_de_inicio', models.DateField(verbose_name='Data de Inicio')),
                ('data_de_fim', models.DateField(verbose_name='Data de Termino')),
                ('objetivo_projeto', models.TextField(max_length=800, verbose_name='Objetivo do Projeto')),
                ('area_projeto', models.CharField(choices=[('', '---------'), ('Comunicação', 'Comunicação'), ('Cultura', 'Cultura'), ('Direitos Humanos e Justiça', 'Direitos Humanos e Justiça'), ('Educação', 'Educação'), ('Meio Ambiente', 'Meio Ambiente'), ('Saúde', 'Saúde'), ('Tecnologia e Produção', 'Tecnologia e Produção'), ('Trabalho', 'Trabalho')], max_length=30, verbose_name='Área do Projeto')),
                ('url_projeto', models.URLField(verbose_name='URL do Projeto')),
                ('tipos_de_acoes', models.CharField(choices=[('', '---------'), ('Projeto', 'Projeto'), ('Evento', 'Evento'), ('Curso', 'Curso')], max_length=10, verbose_name='Tipos de Ações')),
                ('financiador', models.CharField(max_length=30, null=True, verbose_name='Financiador')),
                ('valor_financiado', models.CharField(max_length=30, verbose_name='Valor Financiado')),
                ('edital_financiado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Edital do Financiamento')),
                ('coordenador_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.FileField(blank=True, upload_to='', verbose_name='Relatório')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='coordenador_curso.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_projeto', models.CharField(blank=True, max_length=200)),
                ('lattes', models.CharField(blank=True, max_length=200)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='coordenador_curso.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Bolsistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsista', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to='coordenador_curso.bolsas')),
            ],
        ),
        migrations.AddField(
            model_name='bolsas',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='coordenador_curso.projeto'),
        ),
    ]
