# Generated by Django 3.1 on 2021-01-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador_curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsas',
            name='tipo_bolsa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de bolsa'),
        ),
    ]
