# Generated by Django 3.1 on 2021-01-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=200)),
                ('sobrenome_professor', models.CharField(max_length=200)),
                ('nome_completo', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
